baseURL = 'https://yuchenhsieh.github.io/'
languageCode = 'en-us'
title = 'YuChenHsieh'
theme = "hugo-sustain"

[params]
  avatar = "img/profile.jpg"
  author = "Yu Chen Hsieh"
  # description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "YuChenHsieh"
  Email         = "yo.c.hsieh@gmail.com"
  # Twitter       = "username"
  LinkedIn      = "yu-chen-hsieh-75393515b"
  # Stackoverflow = "username"
  # Medium        = "username"
  # Telegram      = "username"
  # RSS           = "/blog/index.xml"

## Main Menu
# [[menu.main]]
#  name = "blog"
#  weight = 100
#  identifier = "blog"
#  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 100
  url = "/projects/"
# [[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 200
#  url = "/resume/"